language: go

go:
  - 1.8

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter.v1 --install

script:
  - gometalinter.v1
      --deadline=10m --line-length=180 --vendor --vendored-linters
      --disable-all --enable=goconst --enable=gofmt --enable=goimports
      --enable=golint --enable=gosimple --enable=gotype --enable=ineffassign
      --enable=interfacer --enable=lll --enable=misspell --enable=staticcheck
      --enable=test --enable=testify --enable=unconvert --enable=varcheck
      --enable=vet --enable=vetshadow ./...
  - go test -v -race ./...
